version: '3.8'

services:
  # Next.js 애플리케이션 (테스트 환경)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - APP_ENV=test
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=test
      - NODE_ENV=development
      - DATABASE_URL=file:./test.db
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SECRET=test-secret-key-for-testing-only
      - USE_MOCK_AI=true
      - CACHE_PROVIDER=memory
      - STORAGE_PROVIDER=local
      - EMAIL_PROVIDER=mock
      - MOCK_AUTH_ENABLED=true
      - DISABLE_REDIS=true
    volumes:
      # 개발 모드에서 소스 코드 동기화
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      # 테스트 데이터 저장
      - ./uploads/test:/app/uploads/test
      - ./test.db:/app/test.db
    command: npm run dev:test
    networks:
      - test-network

  # WebSocket 서버 (선택적)
  socket:
    build:
      context: .
      dockerfile: Dockerfile.socket
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - APP_ENV=test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge