# Nixpacks configuration for Railway
# Override Python detection and use Node.js

providers = []

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python311"]

[phases.install]
cmds = [
  "echo 'Skipping Python install, this is a Node.js project'",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODE_VERSION = "18"