# Nixpacks configuration for Railway
# Force Node.js provider and fix Python version issue

providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python310"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.10"