[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
nixpacksVersion = "1.17.0"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PYTHON_VERSION = "3.10"