services:
  - type: web
    name: exhell-app
    runtime: node
    repo: https://github.com/LEONFROMWORK/excelapp
    buildCommand: npm install && npm run build:safe
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUILDING
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: exhell-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://exhell.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: ENABLE_REDIS
        value: false
      - key: ENABLE_S3
        value: false
      - key: MOCK_AI
        value: true

databases:
  - name: exhell-db
    plan: starter
    postgresMajorVersion: 15